// apps/client/src/shared/components/ThemeToggle/index.tsx
import { Theme } from '@/shared/enums/Theme'
import { useThemeStore } from '@/shared/store'
import { MoonStar, Sun } from 'lucide-react'

function ThemeToggle({ size = 24 }) {
  const { theme, setTheme } = useThemeStore()

  function toggleTheme() {
    const currentTheme = theme === Theme.DARK ? Theme.LIGHT : Theme.DARK
    setTheme(currentTheme)
  }

  return <div onClick={toggleTheme}>{theme === Theme.DARK ? <Sun size={size} /> : <MoonStar size={size} />}</div>
}

export default ThemeToggle

// apps/admin/src/shared/components/ThemeToggle/index.vue
<script setup lang="ts">
import MoonIcon from '@/assets/icons/MoonIcon.vue'
import SumIcon from '@/assets/icons/SumIcon.vue'
import { ThemeEnum } from '@/shared/enums/ThemeEnum'
import { useThemeStore } from '@/shared/store/useThemeStore'
const themeStore = useThemeStore()

function changeTheme() {
  themeStore.changeTheme(themeStore.theme === ThemeEnum.LIGHT ? ThemeEnum.DARK : ThemeEnum.LIGHT)
}
</script>

<template>
  <div @click="changeTheme">
    <MoonIcon v-if="themeStore.theme === ThemeEnum.LIGHT" />
    <SumIcon v-if="themeStore.theme === ThemeEnum.DARK" />
  </div>
</template>

<style scoped></style>
